export default {
  GET_USER: 'GET_USER',

  MAKE_NEW_CARDS: 'MAKE_NEW_CARDS',
  DELETE_CARDS: 'DELETE_CARDS',
  SELECT_CARD_IDS: 'SELECT_CARD_IDS',
  GET_CARDS_AND_DECKS: 'GET_CARDS_AND_DECKS',

  MAKE_NEW_DECK: 'MAKE_NEW_DECK',
  DELETE_DECK: 'DELETE_DECK',
  ADD_CARDS_TO_DECK: 'ADD_CARDS_TO_DECK',
  REMOVE_CARDS_FROM_DECK: 'REMOVE_CARDS_FROM_DECK',
  SELECT_DECK_ID: 'SELECT_DECK_ID',
  SWAP_DECK: 'SWAP_DECK'
}